name: cicd development workflow for dev env

on: 
  push:
    branches:
    - feat/family

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps: 
    - name: Checkout
      uses: actions/checkout@v2.7.0

    - name: Setup Python
      uses: actions/setup-python@v3.1.3

      
    - name: Install dependencies
      run: pip install -r requirements.txt


  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint app-code
      run: |
        python --version
#        flake8 --extend-ignore E203,W234,E302,E305,E722